// Code generated by Wire. DO NOT EDIT.

//go:generate go run github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package di

import (
	"context"
	"github.com/hiteshpattanayak-tw/url_shortner/internal/app"
	"github.com/hiteshpattanayak-tw/url_shortner/internal/app/handlers"
	"github.com/hiteshpattanayak-tw/url_shortner/internal/app/repository"
	"github.com/hiteshpattanayak-tw/url_shortner/internal/app/router"
	"github.com/hiteshpattanayak-tw/url_shortner/internal/app/service"
)

// Injectors from wire.go:

func InitializeApp(ctx context.Context) (*app.App, error) {
	urlRepository := repository.ProvideNewUrlRepository()
	urlService := service.ProvideUrlService(urlRepository)
	urlShortenerHandler := handlers.ProvideNewUrlShortenerHandler(urlService)
	muxRouter := router.ProvideRouter(urlShortenerHandler)
	appApp := &app.App{
		Router: muxRouter,
	}
	return appApp, nil
}
